[customizations.installer.modules]
disable = ["org.fedoraproject.Anaconda.Modules.Users"]

[customizations.installer.kickstart]
contents = """
lang en_GB.UTF-8
keyboard uk
timezone CET

zerombr
clearpart --all --initlabel
autopart --type=plain
reboot --eject
"""
